### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.oslc-ui#1]

**Comment by AndreyBespamyatnov** [comment]
Hi, could you clarify please what type of CI could you like to integrate here? Thanks

**Comment by berezovskyi** [comment]
Given that https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works is dead, I started to set up GH Actions everywhere, e.g. https://github.com/eclipse/lyo/blob/master/.github/workflows/maven.yml

**Comment by berezovskyi** [comment]
Do you have an alternative suggestion?

**Comment by AndreyBespamyatnov** [comment]
Do we want to use GitHub Actions or Azure? or maybe we are using something else now. I can build the pipeline, actually, we already have it for Gitlab and we can migrate it

**Comment by AndreyBespamyatnov** [comment]
I think we should stay on GitHub Actions to be consistent

**Comment by berezovskyi** [comment]
I think Azure stuff is getting deprecated in a quiet way in favour of Actions https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/migrating-from-azure-pipelines-to-github-actions

**Comment by berezovskyi** [comment]
We are also using https://ci.eclipse.org/lyo/view/1Enabled/ behind the scenes to release to Maven Central and Eclipse Maven because that's where GPG and SSH secrets are. But we can use Actions or anything else for CI builds here. I am not good with the new Jenkinsfile approach but you are welcome to teach me by example :)

**Comment by AndreyBespamyatnov** [comment]
Sure, I added CI to build and collect artifacts
